### ISSUE TITLE
Create a PR including this project to the Open-Source ecosystem map

### ISSUE THREAD

**Issue by julien-boudry** [lzear/votes#110]
https://github.com/CondorcetVote/Condorcet-Voting-Open-Source-Ecosystem-Map#javascript--typescript

With the supported methods and short a description.

**Comment by lzear** [comment]
Hey Julien! Thanks a lot for reaching out!

I always wanted to contact you but I was too shy 😅 
If there's anyway I can collaborate with you, please let me know. I will try working on https://github.com/lzear/votes/issues/111 in the weekend, and I still have plans to open-source my other stuff from https://www.elzear.de/polls but I've been unmotivated so far

**Comment by julien-boudry** [comment]
Hi @Izear

My pleasure.

Your project is probably the most similar and competitive to mine. I didn't realize the evolution for 2 or three years (but Condorcet also!).

Collaboration could be about standardizing the input format. And cross-test vote method.

Currently, we are working on new proportional methods, especially Schulze STV with @LiamM32, and it's hard (to understand, to implement it well and completely, find tests, to write tests). I'm also interested in the Randomized Condorcet method, but not easy too, as I see you have difficulty with too (but you get it).
