### ISSUE TITLE
Next.js production env with side effect

### ISSUE THREAD

**Issue by maiconcarraro** [lzear/votes#75]
I'm still trying to understand what is exactly the root cause, the only thing I know for sure is that it only happens when I try to use the votes import, if I remove the code reference it works fine. 

It's using **InstantRunoff** to calculate results, it **works fine locally**, but once I deploy into Vercel it fails and the only error I got is this one:
![image](https://user-images.githubusercontent.com/13419087/196197731-5120a96f-b7d3-495c-ad5c-c3e32d21a0a3.png)

Any tip how can I investigate it better or what to do? I already sent Vercel a ticket to follow up as well.

Sentry information:
```js
Crashed in non-app: /var/task/node_modules/votes/dist/votes.cjs.prod.js in InstantRunoff.lastRoundQualified
```

**Comment by lzear** [comment]
Hello @maiconcarraro!
Sorry I missed the notification for this issue! Thanks for reporting it!

There were a few uses of `Array.at` which isn't supported by all browsers. I replaced them all.

Can you update the version of `votes` to `2.0.5` and let me know if you still see this issue, or a similar one?

**Comment by maiconcarraro** [comment]
hey @lzear it worked, I also tested w/ `2.0.6`, thank you very much.
